import {api,$,init,escapeHTML as e,dateLabel,empty,toast,showError,clearError,bell} from './app.js';
const page=document.body.dataset.page,task=page==='tareas',base='/'+page,nameKey=task?'titulo':'nombre',dateKey=task?'fecha_entrega':'fecha',singular=task?'tarea':'prueba';
let items=[],editing=null;const dialog=$('#activity-dialog'),form=$('#activity-form');
function render(){const search=$('#search').value.toLocaleLowerCase();const status=$('#filter')?.value||'todas';const rows=items.filter(x=>(x[nameKey]+' '+x.asignatura).toLocaleLowerCase().includes(search)&&(status==='todas'||x.estado===status));$('#item-count').textContent=`${rows.length} ${rows.length===1?singular:singular+'s'}`;
$('#activity-list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Actividad</th><th>Fecha</th><th>Prioridad</th><th>Tiempo</th><th>Acciones</th></tr></thead><tbody>${rows.map(x=>`<tr class="${x.estado==='completada'?'complete':''}"><td><strong>${e(x[nameKey])}</strong><p>${e(x.asignatura)} · Dificultad ${x.dificultad}/5</p>${x.descripcion?`<p>${e(x.descripcion)}</p>`:''}</td><td>${e(dateLabel(x[dateKey],{day:'numeric',month:'short',year:'numeric'}))}</td><td><span class="tag ${e(x.prioridad)}">${e(x.prioridad)}</span></td><td>${x.tiempo_estimado} min</td><td><div class="actions">${task?`<button class="small secondary" data-action="toggle" data-id="${x.id}">${x.estado==='completada'?'Reabrir':'Completar'}</button>`:''}<button class="small ghost" data-action="edit" data-id="${x.id}">Editar</button><button class="small danger" data-action="delete" data-id="${x.id}">Eliminar</button></div></td></tr>`).join('')}</tbody></table></div>`:empty(items.length?'Sin coincidencias':`Tu primera ${singular} empieza aquí`,items.length?'Prueba otra búsqueda o cambia el filtro.':`Agrega una ${singular} con su asignatura y fecha para empezar a organizarte.`);}
async function load(){clearError();try{items=await api(base);render();await bell();}catch(error){showError(error);$('#activity-list').innerHTML=empty('No se pudieron cargar las actividades','Revisa la conexión y vuelve a abrir esta página.');}}
function open(item=null){editing=item;form.reset();clearError('#form-error');$('#dialog-title').textContent=(item?'Editar ':'Nueva ')+singular;if(item)for(const [key,value] of Object.entries(item)){const field=form.elements.namedItem(key);if(field)field.value=value;}dialog.showModal();$('#titulo').focus();}
$('#new-item').onclick=()=>open();$('#close-dialog').onclick=()=>dialog.close();$('#cancel-dialog').onclick=()=>dialog.close();$('#search').oninput=render;if($('#filter'))$('#filter').onchange=render;
form.addEventListener('submit',async event=>{event.preventDefault();clearError('#form-error');const data=Object.fromEntries(new FormData(form));data.dificultad=Number(data.dificultad);data.tiempo_estimado=Number(data.tiempo_estimado);if(task)data.estado=editing?.estado||'pendiente';const button=$('button[type=submit]',form);button.disabled=true;
try{await api(base+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:data});dialog.close();toast('Actividad guardada.');await load();}catch(error){showError(error,'#form-error');}finally{button.disabled=false;}});
$('#activity-list').addEventListener('click',async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const item=items.find(x=>x.id===Number(button.dataset.id));if(!item)return;const action=button.dataset.action;if(action==='edit'){open(item);return;}if(action==='delete'&&!confirm(`¿Eliminar “${item[nameKey]}”? Esta acción no se puede deshacer.`))return;button.disabled=true;try{await api(base+'/'+item.id+(action==='toggle'?'/estado':''),{method:action==='toggle'?'PATCH':'DELETE',...(action==='toggle'?{body:{estado:item.estado==='pendiente'?'completada':'pendiente'}}:{})});toast(action==='delete'?'Actividad eliminada.':'Estado actualizado.');await load();}catch(error){showError(error);button.disabled=false;}});
(async()=>{if(await init()){await load();if(new URLSearchParams(location.search).has('nueva'))open();}})();
